var username = JSON.parse(JSON.parse(localStorage.getItem("persist:nt"))["user"]).username;
var fifthNavBtn = document.getElementsByClassName("nav-list-item")[4];
var fifthNavBtnHref = fifthNavBtn.getElementsByClassName("nav-link")[0].href;
if (fifthNavBtnHref == "https://www.nitrotype.com/class") fifthNavBtn.remove();
var nav = document.getElementsByClassName("header-nav g g--f well well--t")[0];
let friendsBtn = document.createElement("div");
friendsBtn.className = "g-b g-b--2of12";
friendsBtn.style = "width: 20%; max-width: 20%;";
friendsBtn.innerHTML = `<a href="/race/" class="btn btn--primary animate--iconSlam"><svg class="icon icon-friends btn-icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/dist/site/images/icons/icons.css.svg#icon-friends"></use></svg>Start a Friends Race</a>`;
nav.append(friendsBtn);
document.getElementsByClassName("g-b g-b--10of12")[0].style = "width: 63.33333%; max-width: 63.33333%;";
document.getElementsByClassName("btn btn--primary animate--iconSlam")[1].href = "https://www.nitrotype.com/race/" + username;